### PR TITLE
Update plsql.configuration.json

### PR DESCRIPTION
**Pull request by Danieleeee**
Hi,
what is it for /" ?
I added ["\*", "*/"] for autoclosing comments.
Removed [ ] which are never used.

what do you think about?

### CODE REVIEW

**Comment by zabel-xyz** [comment]
what is it for /" ? 
=> to use double-quote.
 I know simple quote is more common in oracle, but double quote can be usefull too,  please don't delete it !
I added ["/*", "*/"] for autoclosing comments. 
=> Ok, this was missing
Removed [ ] which are never used. 
=> Ok, not used

**Comment by Danieleeee** [comment]
Thanks, 
I hope you will soon be able to implement other Pull requests and Issues as well.
Bye.

**Comment by zabel-xyz** [comment]
I push some improvement in plsql.configuration.json
(Not pubilshed yet)

**Comment by zabel-xyz** [comment]
Fix in version 1.1.0

**Pull request closed without merging**
