### PR TITLE
Create plsqlDocumentSymbol.provider.ts

### PR DESCRIPTION
**Pull request by Danieleeee**
Remove bug for somenamepackage variable name:
schermata 2017-06-15 alle 19 49 46

### CODE REVIEW

**Comment by zabel-xyz** [comment]
Ok, I see the problem. But your correction will not fix all issues
"Package varchar2" is removed  but "Procedure varchar2" is still there

I suggest another regexp to fix this issue:
?:create(?:\s+or\s+replace)?\s+)?((\b(?:function|procedure|package)\b(?:\s+body)?)\s+(?:\w+\.)?\w+)

**Comment by Danieleeee** [comment]
Ok

**Comment by Danieleeee** [comment]
Do I have to include the change you suggested or you think about it?

**Comment by zabel-xyz** [comment]
No, you have nothing todo. I'll make an update to fix this problem (perhaps this weekend...)

**Pull request closed without merging**
